finalize the fix

diff --git a/.github/workflows/0.terraform.backend.yml b/.github/workflows/0.terraform.backend.yml
--- a/.github/workflows/0.terraform.backend.yml
+++ b/.github/workflows/0.terraform.backend.yml
@@ -23,8 +23,10 @@ jobs:
             storage_account_name="terraform${RANDOM}${RANDOM}"
             echo "Generated Storage Account Name: $storage_account_name"
             echo "TERRAFORM_STORAGE_ACCOUNT_NAME=$storage_account_name" >> $GITHUB_ENV
+            gh variable set TERRAFORM_STORAGE_ACCOUNT_NAME -b ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }}
+
           else
-            echo "Using existing secret for TERRAFORM_STORAGE_ACCOUNT_NAME."
+            echo "Using existing variable for TERRAFORM_STORAGE_ACCOUNT_NAME."
             echo "TERRAFORM_STORAGE_ACCOUNT_NAME=${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
           fi
           echo "Storage Account Name: ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }}"
@@ -40,26 +42,23 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      # - name: Create the Storage Account
-      #   run: |
-      #     az storage account create \
-      #         --name  ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }} \
-      #         --resource-group ${{ vars.AZURE_GROUP_NAME }} \
-      #         --location ${{ vars.AZURE_LOCATION }} \
-      #         --sku Standard_LRS \
-      #         --allow-blob-public-access false
-      #     if [ $? -ne 0 ]; then
-      #       echo "Failed to create the storage account"
-      #       exit 1
-      #     fi
-
-      # - name: Create the Storage Container
-      #   run: |
-      #     az storage container create \
-      #         --name ${{ env.TERRAFORM_STORAGE_CONTAINER_NAME }} \
-      #         --account-name ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }}
-
-      - name: Save the name in the GitHub Action secret
+      - name: Create the Storage Account
         run: |
-          gh variable set TERRAFORM_STORAGE_ACCOUNT_NAME -b ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }}
+          az storage account create \
+              --name  ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }} \
+              --resource-group ${{ vars.AZURE_GROUP_NAME }} \
+              --location ${{ vars.AZURE_LOCATION }} \
+              --sku Standard_LRS \
+              --allow-blob-public-access false
+          if [ $? -ne 0 ]; then
+            echo "Failed to create the storage account"
+            exit 1
+          fi
+
+      - name: Create the Storage Container
+        run: |
+          az storage container create \
+              --name ${{ env.TERRAFORM_STORAGE_CONTAINER_NAME }} \
+              --account-name ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }}
+
 
